_side = _this param [0];
_class = _this param [1];

_returnValue = [];

if(_side == west) then {
	if(_class == "AR") then {_returnValue = [["rhs_weap_m249_pip_L_para","","","rhsusf_acc_ACOG_RMR",["rhsusf_200rnd_556x45_mixed_box",200],[],"rhsusf_acc_grip4_bipod"],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_SAW",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1],["HandGrenade",1,1],["rhsusf_200rnd_556x45_mixed_box",2,200]]],["rhsusf_assault_eagleaiii_ucp",[["rhsusf_200rnd_556x45_mixed_box",1,200]]],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Crew") then {_returnValue = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_Rifleman",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",5,30],["HandGrenade",1,1]]],["rhsusf_assault_eagleaiii_ucp",[["ToolKit",1]]],"rhsusf_cvc_green_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Engi") then {_returnValue = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_Rifleman",[["ACE_DefusalKit",1],["ACE_Clacker",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",4,30],["HandGrenade",1,1]]],["rhsusf_assault_eagleaiii_ucp",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",3,1],["SatchelCharge_Remote_Mag",1,1]]],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "HG") then {_returnValue = [["rhs_weap_m240B","","","rhsusf_acc_ACOG_RMR",["rhsusf_100Rnd_762x51_m62_tracer",100],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_SAW",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1],["HandGrenade",1,1],["rhsusf_100Rnd_762x51_m62_tracer",3,100]]],[],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Mark") then {_returnValue = [["rhs_weap_XM2010","","","rhsusf_acc_LEUPOLDMK4_2",["rhsusf_5Rnd_300winmag_xm2010",5],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_spcs_ucp_sniper",[["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["rhsusf_mag_17Rnd_9x19_FMJ",5,17],["SmokeShell",2,1],["HandGrenade",1,1],["rhsusf_5Rnd_300winmag_xm2010",20,5]]],[],"rhsusf_ach_helmet_headset_ess_ucp","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Med") then {_returnValue = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_Medic",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",4,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",4,30],["MiniGrenade",1,1]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_bloodIV_500",10],["ACE_elasticBandage",40],["ACE_packingBandage",20],["ACE_epinephrine",15],["ACE_morphine",15],["ACE_splint",20],["ACE_tourniquet",10],["ACE_bloodIV",5]]],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Pilot_H") then {_returnValue = [["rhs_weap_m4_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_acu_ucp",[["ACE_elasticBandage",15],["ACE_epinephrine",3],["ACE_morphine",2],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_splint",2],["ACE_tourniquet",4],["SmokeShellBlue",1,1]]],["rhsusf_spcs_ucp",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1]]],["rhsusf_assault_eagleaiii_ucp",[["ToolKit",1],["rhsusf_patrolcap_ucp",1]]],"FU_NVG_helm","G_Spectacles_Tinted",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Pilot_P") then {_returnValue = [[],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["U_B_PilotCoveralls",[]],[],["rhsusf_assault_eagleaiii_ucp",[["ACE_elasticBandage",5],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_MapTools",1],["rhsusf_patrolcap_ucp",1],["ToolKit",1],["rhsusf_mag_17Rnd_9x19_FMJ",1,17],["rhsusf_spcs_ucp",false],["rhs_uniform_acu_ucp",false]]],"H_PilotHelmetFighter_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""]]};
	if(_class == "Rifle") then {_returnValue = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_Rifleman",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",5,30],["HandGrenade",1,1]]],["rhsusf_assault_eagleaiii_ucp",[]],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "LAT") then {_returnValue = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_Rifleman",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",5,30],["HandGrenade",1,1]]],["rhsusf_assault_eagleaiii_ucp",[]],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "MAT") then {_returnValue = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],["launch_MRAWS_olive_rail_F","","","",["MRAWS_HEAT_F",1],[],""],[],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_spcs_ucp_rifleman",[["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",4,30],["MiniGrenade",1,1]]],["rhsusf_assault_eagleaiii_ucp",[["MRAWS_HEAT_F",3,1],["MRAWS_HE_F",1,1]]],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "SL") then {_returnValue = [["rhs_weap_m4a1_m320","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],["1Rnd_HE_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_cu_ucp",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["ACE_microDAGR",1],["SmokeShellBlue",1,1]]],["rhsusf_iotv_ucp_Squadleader",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShell",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",5,30],["HandGrenade",1,1]]],["FU_radio_p_blk",[["1Rnd_HE_Grenade_shell",7,1],["1Rnd_Smoke_Grenade_shell",5,1]]],"rhsusf_ach_helmet_headset_ess_ucp","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
};

if(_side == east) then {
	if(_class == "AR") then {_returnValue = [["rhs_weap_pkm","","","",["150Rnd_762x54_Box_Tracer",150],[],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ACE_EntrenchingTool",1],["rhs_mag_9x19_17",2,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1],["150Rnd_762x54_Box_Tracer",2,150]]],["rhs_assault_umbts",[["150Rnd_762x54_Box_Tracer",3,150]]],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Crew") then {_returnValue = [["rhs_weap_aks74un","rhs_acc_dtk1983","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ToolKit",1],["rhs_30Rnd_545x39_7N10_AK",4,30],["SmokeShell",2,1],["rhs_mag_9x19_17",2,17]]],["FU_radio_p_gre",[]],"rhs_tsh4","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Engi") then {_returnValue = [["rhs_weap_ak74m","rhs_acc_dtk","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ACE_EntrenchingTool",1],["ACE_DefusalKit",1],["ACE_Clacker",1],["rhs_30Rnd_545x39_7N10_AK",10,30],["rhs_mag_9x19_17",2,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1]]],["rhs_assault_umbts_engineer_empty",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",3,1],["SatchelCharge_Remote_Mag",1,1]]],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "HG") then {_returnValue = [["rhs_weap_pkp","","","rhs_acc_pkas",["rhs_100Rnd_762x54mmR",100],[],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ACE_EntrenchingTool",1],["rhs_mag_9x19_17",2,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1],["rhs_100Rnd_762x54mmR",1,100]]],["rhs_assault_umbts",[["rhs_100Rnd_762x54mmR",2,100]]],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Mark") then {_returnValue = [["rhs_weap_svdp","","","rhs_acc_pso1m21",["rhs_10Rnd_762x54mmR_7N1",10],[],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_ATragMX",1],["rhs_mag_9x19_17",4,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1],["rhs_10Rnd_762x54mmR_7N1",15,10]]],[],"rhs_6b28_ess","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Med") then {_returnValue = [["rhs_weap_ak74m","rhs_acc_dtk","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ACE_EntrenchingTool",1],["rhs_30Rnd_545x39_7N10_AK",11,30],["rhs_mag_9x19_17",2,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1]]],["rhs_assault_umbts",[["ACE_elasticBandage",40],["ACE_packingBandage",20],["ACE_morphine",15],["ACE_epinephrine",15],["ACE_bloodIV_500",10],["ACE_splint",20],["ACE_tourniquet",10],["ACE_bloodIV",5]]],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Pilot_H") then {_returnValue = [[],[],["rhs_weap_pp2000_folded","","","",["rhs_mag_9x19mm_7n21_44",44],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ToolKit",1],["rhs_mag_9x19mm_7n21_44",4,44],["SmokeShell",2,1]]],["FU_radio_p_gre",[]],"FU_NVG_helm_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Pilot_P") then {_returnValue = [[],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["U_O_PilotCoveralls",[]],[],["rhs_assault_umbts",[["ToolKit",1],["ACE_elasticBandage",5],["ACE_epinephrine",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_morphine",1],["rhs_fieldcap_digi2",1],["SmokeShellRed",1,1],["rhs_mag_9x19_17",2,17],["rhs_uniform_emr_patchless",false],["rhs_6b23_digi",false]]],"H_PilotHelmetFighter_O","G_Spectacles_Tinted",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""]]};
	if(_class == "Rifle") then {_returnValue = [["rhs_weap_ak74m","rhs_acc_dtk","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ACE_EntrenchingTool",1],["rhs_30Rnd_545x39_7N10_AK",11,30],["rhs_mag_9x19_17",2,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1]]],[],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "LAT") then {_returnValue = [["rhs_weap_ak74m","rhs_acc_dtk","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],["rhs_weap_rpg26","","","",[],[],""],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_6sh116",[["ACE_EntrenchingTool",1],["rhs_30Rnd_545x39_7N10_AK",11,30],["rhs_mag_9x19_17",2,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1]]],[],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "MAT") then {_returnValue = [["rhs_weap_ak74m","rhs_acc_dtk","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],["rhs_weap_rpg7","","","rhs_acc_pgo7v3",["rhs_rpg7_PG7V_mag",1],[],""],[],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_digi_6sh92",[["ACE_EntrenchingTool",1],["rhs_30Rnd_545x39_7N10_AK",8,30],["SmokeShell",2,1],["rhs_mag_rgo",1,1]]],["rhs_rpg_empty",[["rhs_rpg7_PG7V_mag",3,1],["rhs_rpg7_OG7V_mag",1,1]]],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "SL") then {_returnValue = [["rhs_weap_ak74m_gp25","rhs_acc_dtk","","",["rhs_30Rnd_545x39_7N10_AK",30],["rhs_VOG25",1],""],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["rhs_uniform_msv_emr",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_microDAGR",1],["SmokeShellRed",1,1]]],["rhs_6b23_digi_6sh92_headset_mapcase",[["ACE_EntrenchingTool",1],["rhs_mag_9x19_17",2,17],["SmokeShell",2,1],["rhs_mag_rgo",1,1],["rhs_30Rnd_545x39_7N10_AK",8,30]]],["FU_radio_p_gre",[["rhs_VOG25",7,1],["rhs_GRD40_White",5,1]]],"rhs_6b28_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
};

if(_side == resistance) then {
	if(_class == "AR") then {_returnValue = [["rhs_weap_pkm","","","",["150Rnd_762x54_Box_Tracer",150],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_C_Soldier_Para_4_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_oli",[["SmokeShell",2,1],["MiniGrenade",1,1],["10Rnd_9x21_Mag",2,10],["150Rnd_762x54_Box_Tracer",1,150]]],["B_AssaultPack_khk",[["150Rnd_762x54_Box_Tracer",3,150]]],"H_Watchcap_camo","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Crew") then {_returnValue = [["rhs_weap_aks74u","rhs_acc_pgs64_74u","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_G_Story_Protagonist_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_blk",[["ToolKit",1],["SmokeShell",2,1],["10Rnd_9x21_Mag",2,10]]],["FU_radio_p_blk",[["rhs_30Rnd_545x39_7N10_AK",5,30]]],"rhs_tsh4","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Engi") then {_returnValue = [["rhs_weap_akm","rhs_acc_dtkakm","","",["rhs_30Rnd_762x39mm",30],[],""],[],["ACE_VMM3","","","",[],[],""],["U_BG_Guerilla2_2",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",4]]],["V_TacVest_blk",[["ACE_DefusalKit",1],["ACE_Clacker",1],["SmokeShell",2,1],["MiniGrenade",1,1],["rhs_30Rnd_762x39mm",2,30],["rhs_30Rnd_762x39mm_tracer",3,30]]],["B_TacticalPack_oli",[["ToolKit",1],["DemoCharge_Remote_Mag",3,1],["SatchelCharge_Remote_Mag",1,1],["rhs_30Rnd_762x39mm",1,30]]],"H_Cap_headphones","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "HG") then {_returnValue = [["rhs_weap_fnmag","","","",["rhsusf_100Rnd_762x51_m62_tracer",100],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_C_Soldier_Para_4_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_oli",[["SmokeShell",2,1],["MiniGrenade",1,1],["10Rnd_9x21_Mag",2,10],["rhsusf_100Rnd_762x51_m62_tracer",2,100]]],["B_AssaultPack_khk",[["rhs_30Rnd_762x39mm_tracer",2,30],["rhs_30Rnd_762x39mm",2,30],["rhsusf_100Rnd_762x51_m62_tracer",3,100]]],"H_Watchcap_camo","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Mark") then {_returnValue = [["rhs_weap_kar98k","","","",["rhsgref_5Rnd_792x57_kar98k",5],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_C_Soldier_Para_4_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_oli",[["SmokeShell",2,1],["MiniGrenade",1,1],["10Rnd_9x21_Mag",5,10],["rhsgref_5Rnd_792x57_kar98k",20,5]]],[],"H_Booniehat_oli","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Med") then {_returnValue = [["rhs_weap_akm","rhs_acc_dtkakm","","",["rhs_30Rnd_762x39mm",30],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_G_Story_Protagonist_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVestIR_blk",[["SmokeShell",2,1],["MiniGrenade",1,1],["10Rnd_9x21_Mag",1,10],["rhs_30Rnd_762x39mm",5,30],["rhs_30Rnd_762x39mm_tracer",4,30]]],["B_TacticalPack_blk",[["ACE_elasticBandage",40],["ACE_packingBandage",20],["ACE_bloodIV_500",10],["ACE_bloodIV",5],["ACE_epinephrine",15],["ACE_morphine",15],["ACE_tourniquet",10],["ACE_splint",20]]],"H_Cap_blk_ION","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Pilot_H") then {_returnValue = [["rhs_weap_aks74u","rhs_acc_pgs64_74u","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_G_Story_Protagonist_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_blk",[["ToolKit",1],["SmokeShell",2,1],["10Rnd_9x21_Mag",2,10]]],["FU_radio_p_blk",[["rhs_30Rnd_545x39_7N10_AK",5,30]]],"rhs_tsh4","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Pilot_P") then {_returnValue = [["rhs_weap_aks74u","rhs_acc_pgs64_74u","","",["rhs_30Rnd_545x39_7N10_AK",30],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_G_Story_Protagonist_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_blk",[["ToolKit",1],["SmokeShell",2,1],["10Rnd_9x21_Mag",2,10]]],["FU_radio_p_blk",[["rhs_30Rnd_545x39_7N10_AK",5,30]]],"rhs_tsh4","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "Rifle") then {_returnValue = [["rhs_weap_akm","rhs_acc_dtkakm","","",["rhs_30Rnd_762x39mm",30],[],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_C_Soldier_Para_1_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_oli",[["SmokeShell",2,1],["MiniGrenade",1,1],["10Rnd_9x21_Mag",1,10],["rhs_30Rnd_762x39mm",3,30],["rhs_30Rnd_762x39mm_tracer",3,30]]],["B_AssaultPack_khk",[["rhs_30Rnd_762x39mm_tracer",2,30],["rhs_30Rnd_762x39mm",2,30]]],"H_Cap_headphones","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "LAT") then {_returnValue = [["rhs_weap_akm","rhs_acc_dtkakm","","",["rhs_30Rnd_762x39mm",30],[],""],["rhs_weap_m72a7","","","",[],[],""],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["U_I_C_Soldier_Para_1_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_oli",[["SmokeShell",2,1],["MiniGrenade",1,1],["10Rnd_9x21_Mag",1,10],["rhs_30Rnd_762x39mm",3,30],["rhs_30Rnd_762x39mm_tracer",3,30]]],["B_AssaultPack_khk",[["rhs_30Rnd_762x39mm_tracer",2,30],["rhs_30Rnd_762x39mm",2,30]]],"H_Cap_headphones","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "MAT") then {_returnValue = [["rhs_weap_akm","rhs_acc_dtkakm","","",["rhs_30Rnd_762x39mm",30],[],""],["rhs_weap_rpg7","","","rhs_acc_pgo7v3",["rhs_rpg7_PG7V_mag",1],[],""],[],["U_I_C_Soldier_Para_3_F",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_oli",[["SmokeShell",2,1],["MiniGrenade",1,1],["rhs_30Rnd_762x39mm",3,30],["rhs_30Rnd_762x39mm_tracer",3,30]]],["rhs_rpg_empty",[["rhs_rpg7_PG7V_mag",3,1],["rhs_rpg7_OG7V_mag",1,1]]],"H_Bandanna_sgg","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
	if(_class == "SL") then {_returnValue = [["rhs_weap_akm_gp25","rhs_acc_dtkakm","","",["rhs_30Rnd_762x39mm",30],["rhs_VOG25",1],""],[],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["FU_Uni_p_pmc",[["ACE_elasticBandage",10],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_packingBandage",5],["ACE_microDAGR",1],["SmokeShellGreen",1,1]]],["V_TacVest_oli",[["SmokeShell",2,1],["MiniGrenade",1,1],["10Rnd_9x21_Mag",1,10],["rhs_30Rnd_762x39mm_tracer",3,30],["rhs_30Rnd_762x39mm",3,30]]],["FU_radio_p_gre",[["rhs_GRD40_White",5,1],["rhs_VOG25",7,1]]],"H_Cap_headphones","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
};

if(_side == civilian) then {
	_returnValue = [];
};

_returnValue;

